apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.naming.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "common.labels.selectorLabels" . | nindent 6 }}
  template:
    metadata:
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8}}
{{- end }}
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      # Switching from dedicated service account to default one must be
      # done explicitly, otherwise upgrade fails, trying to use old
      # service account.
      serviceAccount: default
      {{- with include "common.securityContext.pod" . }}
      securityContext:
        {{- . | nindent 8 -}}
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- include "common.images.renderPullSecrets" ( dict "pullSecrets" ( list .Values.image.pullSecrets ) "context" .) | nindent 8 -}}
      {{- end }}
      containers:
      - name: {{ include "common.naming.name" . }}
        image: {{ include "common.images.image" ( dict "imageRoot" .Values.image "context" .) }}
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        {{- with include "common.securityContext.container" . }}
        securityContext:
          {{- . | nindent 10 }}
        {{- end }}
        env:
        - name: clusterName
          value: {{ include "common.cluster" . }}
        ports:
          - containerPort: 8443
            protocol: TCP
        volumeMounts:
        - name: tls-key-cert-pair
          mountPath: /etc/tls-key-cert-pair
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}
      volumes:
      - name: tls-key-cert-pair
        secret:
          secretName: {{ include "common.naming.fullname" . }}-admission
      {{- if $.Values.priorityClassName }}
      priorityClassName: {{ $.Values.priorityClassName }}
      {{- end }}
      {{- with include "common.nodeSelector" . }}
      nodeSelector:
        {{- . | nindent 8 -}}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- with include "common.affinity" . }}
      affinity:
        {{- . | nindent 8 -}}
      {{- end }}
