apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.naming.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 4 }}
