language: go

services:
  - docker

go: 
  - 1.11.x

env:
  - GO111MODULE=on

install: true

jobs:
  include:
    - stage: test
      name: "Lint"
      script: make lint
    - script: make test
      name: "Unit Tests"
    - stage: build
      name: "Build Webhook"
      script: make webhook
    - script: make cert-manager
      name: "Build cert-manager"

notifications:
  email: false