language: go
sudo: required
dist: xenial
services:
  - docker

go:
  - 1.11.x

env:
  global:
    - GO111MODULE=on
    - E2E_SETUP_MINIKUBE=yes
    - E2E_SETUP_KUBECTL=yes
    - E2E_START_MINIKUBE=yes
    - E2E_MINIKUBE_DRIVER=none
    - E2E_SUDO=sudo

# The default install command would be 'go get -t -v ./...', but this is done when running the "Unit Tests" by go test.
# By setting it to 'true', we skip the install step.
install: true

cache:
  directories:
    - $GOPATH/pkg/mod

e2e-stage: &e2e-stage
  stage: "E2E Tests"
  script: make e2e-test

jobs:
  include:
    - stage: test
      name: "Lint"
      script: make lint
    - name: "Unit tests"
      script: make test
    - stage: build
      name: "Build webhook container"
      script: make build-container
    - <<: *e2e-stage
      env:
        - E2E_KUBERNETES_VERSION=v1.9.0
    - <<: *e2e-stage
      env:
        - E2E_KUBERNETES_VERSION=v1.10.0
    # K8s v1.11.0 doesn't seem to work well in travis
    # - <<: *e2e-stage
    #   env:
    #     - E2E_KUBERNETES_VERSION=v1.11.0
    - <<: *e2e-stage
      env:
        - E2E_KUBERNETES_VERSION=v1.12.0

# safelist
branches:
  only:
  - master

notifications:
  email: false
