apiVersion: v1
kind: ServiceAccount
metadata:
  name: newrelic-metadata-injection-service-account
  labels:
    app: newrelic-metadata-injection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newrelic-metadata-injection-cluster-role
  labels:
    app: newrelic-metadata-injection
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: newrelic-metadata-injection-cluster-role-binding
  labels:
    app: newrelic-metadata-injection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: newrelic-metadata-injection-cluster-role
subjects:
- kind: ServiceAccount
  name: newrelic-metadata-injection-service-account
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: newrelic-metadata-injection-deployment
  labels:
    app: newrelic-metadata-injection
spec:
  replicas: 1 # Do not increase this, certificates are created in the container and will conflict if replicas > 1.
  template:
    metadata:
      labels:
        app: newrelic-metadata-injection
    spec:
      serviceAccountName: newrelic-metadata-injection-service-account
      containers:
      - name: metadata-injector
        image: quay.io/newrelic/k8s-metadata-injector-dev
        # imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: newrelic-metadata-injection-svc
  labels:
    app: newrelic-metadata-injection
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: newrelic-metadata-injection
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: newrelic-metadata-injection-cfg
  labels:
    app: newrelic-metadata-injection
webhooks:
- name: metadata-injection.newrelic.com
  clientConfig:
    service:
      name: newrelic-metadata-injection-svc
      namespace: default
      path: "/mutate"
    caBundle: ""
  rules:
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  namespaceSelector:
    matchLabels:
      newrelic-metadata-injection: enabled
  failurePolicy: Ignore