apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: newrelic-metadata-injection-deployment
  labels:
    app: newrelic-metadata-injection
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: newrelic-metadata-injection
    spec:
      containers:
      - name: metadata-injector
        image: docker.coscale.com:5000/fryckbosch/newrelic-k8s-metadata-injector:v1
        imagePullPolicy: Always
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/webhook/certs
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: newrelic-metadata-injection-certs
---
apiVersion: v1
kind: Service
metadata:
  name: newrelic-metadata-injection-svc
  labels:
    app: newrelic-metadata-injection
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: newrelic-metadata-injection
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: newrelic-metadata-injection-cfg
  labels:
    app: newrelic-metadata-injection
webhooks:
- name: metadata-injection.newrelic.com
  clientConfig:
    service:
      name: newrelic-metadata-injection-svc
      namespace: default
      path: "/mutate"
    caBundle: "${CA_BUNDLE}"
  rules:
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  namespaceSelector:
    matchLabels:
      newrelic-metadata-injection: enabled
  failurePolicy: Ignore