{{- if (and (not .Values.customTLSCertificate) (not .Values.certManager.enabled)) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.naming.fullname" . }}-admission-create
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app: {{ include "common.naming.name" . }}-admission-create
spec:
  template:
    metadata:
      name: {{ include "common.naming.fullname" . }}-admission-create
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app: {{ include "common.naming.name" . }}-admission-create
    spec:
      {{- if .Values.jobImage.pullSecrets }}
      imagePullSecrets:
        {{- include "common.images.renderPullSecrets" ( dict "pullSecrets" ( list .Values.jobImage.pullSecrets ) "context" .) | nindent 8 -}}
      {{- end }}
      containers:
        - name: create
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.jobImage "context" .) }}
          imagePullPolicy: {{ .Values.jobImage.pullPolicy }}
          args:
            - create
            - --host={{ include "common.naming.fullname" . }},{{ include "common.naming.fullname" . }}.{{ .Release.Namespace }}.svc
            - --namespace={{ .Release.Namespace }}
            - --secret-name={{ include "common.naming.fullname" . }}-admission
            - --cert-name=tls.crt
            - --key-name=tls.key
          {{- if .Values.jobImage.volumeMounts }}
          volumeMounts:
          {{- include "tplvalues.render" ( dict "value" .Values.jobImage.volumeMounts "context" $ ) | nindent 10 }}
          {{- end }}
      {{- if .Values.jobImage.volumes }}
      volumes:
      {{- include "tplvalues.render" ( dict "value" .Values.jobImage.volumes "context" $ ) | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ include "common.naming.fullname" . }}-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
{{- end }}
