{{- if (and (not .Values.customTLSCertificate) (not .Values.certManager.enabled)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nri-metadata-injection.fullname.admission" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ include "nri-metadata-injection.name.admission" . }}
    {{- include "newrelic.common.labels" . | nindent 4 }}
{{- end }}
