name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e-kubernetes:
    name: Kuebrnetes E2E tests
    runs-on: ubuntu-18.04 # required by manusa/actions-setup-minikube@v2.0.1
    env:
      E2E_MINIKUBE_DRIVER: docker
    strategy:
      matrix:
        k8s_version:
          - v1.16.15
          - v1.17.14
          - v1.18.12
    steps:
      - uses: actions/checkout@v2
      - run: make # If using `docker` as minikube driver, image should not get rebuilt by `make e2e-test`
      - uses: manusa/actions-setup-minikube@v2.0.1
        with:
          minikube version: v1.15.1
          kubernetes version: ${{ matrix.k8s_version }}
          driver: ${{ env.E2E_MINIKUBE_DRIVER }}
      - run: make e2e-test
