# This action requires that any PR should touch at
# least one CHANGELOG file.

name: changelog

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  check-changelog:
    permissions:
      contents: read
      pull-requests: read
    uses: newrelic/k8s-agents-automation/.github/workflows/reusable-changelog.yml@main
